### ISSUE TITLE
connecting to local Elasticsearch cluster ?

### ISSUE THREAD

**Issue by nihilson** [foundit/elasticsearch-transport-module#4]
The readme says..  "it will only enable its authentication and SSL support when connecting to a Found-hosted Elasticsearch cluster".  Can I make use of this elasticsearch-transport-module to enable authentication & SSL when connecting to my local Elasticseach cluster? If yes, any pointers on how to achieve it ?

**Comment by beiske** [comment]
No, have a look at Shield.

**Comment by nihilson** [comment]
could you please explain a little more on why "No" ?

**Comment by beiske** [comment]
Well, it's open source, so you can legally do whatever you want with it, but it requires support for ssl on the server side and Elasticsearch does not provide that without the Shield plugin. Shield has it's own plugin for the client so with Shield this plugin is not only not needed, but probably not compatible either.

**Comment by nihilson** [comment]
Ok.. You mean to say the Found-hosted Elasticsearch cluster has its server side SSL enablement done to be compatible with this transport module right ?

**Comment by beiske** [comment]
It's really the other way around. This plugin does what is required to tunnel the es transport protocol over SSL and adds the necessary information for the proxies in front of found hosted clusters to authenticate and forward traffic to the correct cluster.

**Comment by beiske** [comment]
This plugin just does not make any sense for clusters that are not running behind the proxies we use at Found.

**Comment by beiske** [comment]
If you feel like it, there is nothing stopping you from implementing a proxy compatible with this plugin, but in that case I think it's cheaper to just buy Shield or have a look at some other ssl tunneling software.

**Comment by nkvoll** [comment]
Hey @nihilson, thanks for an interesting question.

This repository only contains the client-side parts of the SSL which can be enabled for a Transport Client and will not work out of the box for the server-side handling of the SSL. By default, this SSL termination isn't something that Elasticsearch supports out of the box, but these features are part of the commercial plugin called [Shield](https://www.elastic.co/products/shield).

If Shield is not an option for you, I'm sure the code in this repository that handles SSL can be useful, but other parts like the keep-alives, and authentication will need to be stripped. Additionally, it would have to be adapted to not only work on Transport connections, but also Node connections, which may be non-trivial, I haven't looked much into it as it wasn't one of our use-cases when writing this module :)

Hope this answers your question!

**Comment by nihilson** [comment]
that explains..  Thanks !!
